name: Render lineplot

on:
  push:
    paths:
      - swedbank.csv
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-lineplot:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r env/requirements.txt

      - name: generate lineplot
        run: python bin/lineplot.py

      - name: Commit & Push
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add images/lineplot.png
          git diff-index --quiet HEAD || git commit -m "Render lineplot.png @ $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin